In [8]:
pip install pandas numpy scikit-learn

Requirement already satisfied: pandas in c:\users\divya\conda_envs\venv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\divya\conda_envs\venv\lib\site-packages (2.2.2)
Collecting scikit-learn
  Using cached scikit_learn-1.6.1-cp312-cp312-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\divya\conda_envs\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\divya\conda_envs\venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\divya\conda_envs\venv\lib\site-packages (from pandas) (2025.1)
Collecting scipy>=1.6.0 (from scikit-learn)
  Using cached scipy-1.15.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\divya\conda_envs\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached scikit_learn-1.6.1-cp312-cp312-win_amd64.whl (11.1 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.15.1-cp312-cp312-win_amd64.whl (43.6 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.1 threadpoolctl-3.5.0
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install pandas

Requirement already satisfied: pandas in c:\users\divya\conda_envs\venv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\divya\conda_envs\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\divya\conda_envs\venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\divya\conda_envs\venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\divya\conda_envs\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [10]:
##Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
##Preprocessing the data 
###Drop irrelevant columns

data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [12]:
##Encode Categorical variables 
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [13]:
##Onehot encode 'Geography'

from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [16]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [15]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [17]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [18]:
##Combine one hot encoder columns with the original data 
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [20]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [19]:
## Save the encoders and scaler 

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [22]:
##Divide the dataset into independent and dependent features 

X=data.drop('Exited',axis=1)
y=data['Exited']

##Split the data in traning and testing sets 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

##Scale these features 
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [23]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [25]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [26]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

## When we start Creating ANN
### Sequential Network 
###  Dense 
###  Activation function(sigmoid,tan h,ReLU,leaky ReLU )
### Optimizer(Use fro Back propogation->Updating the weights)
### Loss function
### Metrics->Accuracy
### Traning->Logs->Folder->Tensorboard->Visualization

### ANN implementation

In [2]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\divya\conda_envs\venv\lib\site-packages (2.18.0)
Requirement already satisfied: tensorflow-intel==2.18.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow) (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (25.1.24)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (75.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.70.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.8.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.12.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in c:\users\divya\conda_envs\venv\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in c:\users\divya\conda_envs\venv\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in c:\users\divya\conda_envs\venv\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.14.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\divya\conda_envs\venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\divya\conda_envs\venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\divya\conda_envs\venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\divya\conda_envs\venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2025.1.31)
Requirement already satisfied: markdown>=2.6.8 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\divya\conda_envs\venv\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\divya\conda_envs\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\divya\conda_envs\venv\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\divya\conda_envs\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [11]:
from sklearn.model_selection import train_test_split

In [17]:
from sklearn.datasets import load_digits  # Example dataset
from sklearn.model_selection import train_test_split

# Load dataset
data = load_digits()
X, y = data.data, data.target  # Define features (X) and labels (y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train shape: (1437, 64)
y_train shape: (1437,)

In [8]:
print(X.shape)  # Check if X is defined and has data

NameError: name 'X' is not defined

In [18]:
print("X_train:", type(X_train), X_train.shape if 'X_train' in locals() else "Not defined")

X_train: <class 'numpy.ndarray'> (1437, 64)

In [21]:
(X_train.shape[1],)

(64,)

In [22]:
##Build Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ##HL1 Connected with input layer 
    Dense(32,activation='relu'),  ##HL2
    Dense(1,activation='sigmoid')  ##Output layer
    
])

c:\Users\Divya\conda_envs\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [23]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,273 (24.50 KB)

 Trainable params: 6,273 (24.50 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [27]:
#compile the model

model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [41]:
##Set up the Tensorboard

from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" +datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [32]:
##Set up Early Stopping

early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [34]:
##Set up Early Stopping

early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [35]:
### Train the model

history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1030 - loss: -261199970304.0000 - val_accuracy: 0.0778 - val_loss: -287175573504.0000
Epoch 2/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0949 - loss: -284066840576.0000 - val_accuracy: 0.0778 - val_loss: -294281150464.0000
Epoch 3/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1067 - loss: -280982781952.0000 - val_accuracy: 0.0778 - val_loss: -301389086720.0000
Epoch 4/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1182 - loss: -289612267520.0000 - val_accuracy: 0.0778 - val_loss: -308648116224.0000
Epoch 5/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1039 - loss: -303030730752.0000 - val_accuracy: 0.0778 - val_loss: -316015837184.0000
Epoch 6/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1127 - loss: -295608254464.0000 - val_accuracy: 0.0778 - val_loss: -323371368448.0000
Epoch 7/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1088 - loss: -306734891008.0000 - val_accuracy: 0.0778 - val_loss: -331009163264.0000
Epoch 8/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1160 - loss: -318248910848.0000 - val_accuracy: 0.0778 - val_loss: -338680741888.0000
Epoch 9/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.1141 - loss: -329008316416.0000 - val_accuracy: 0.0778 - val_loss: -346365820928.0000
Epoch 10/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1047 - loss: -326954319872.0000 - val_accuracy: 0.0778 - val_loss: -354257076224.0000
Epoch 11/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1084 - loss: -343470768128.0000 - val_accuracy: 0.0778 - val_loss: -362188177408.0000
Epoch 12/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0971 - loss: -342296166400.0000 - val_accuracy: 0.0778 - val_loss: -370216534016.0000
Epoch 13/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1087 - loss: -358148800512.0000 - val_accuracy: 0.0778 - val_loss: -378411286528.0000
Epoch 14/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1129 - loss: -369715675136.0000 - val_accuracy: 0.0778 - val_loss: -386647687168.0000
Epoch 15/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1113 - loss: -372652736512.0000 - val_accuracy: 0.0778 - val_loss: -394934091776.0000
Epoch 16/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1172 - loss: -368804134912.0000 - val_accuracy: 0.0778 - val_loss: -403399016448.0000
Epoch 17/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1024 - loss: -385573847040.0000 - val_accuracy: 0.0778 - val_loss: -412025061376.0000
Epoch 18/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1115 - loss: -392477343744.0000 - val_accuracy: 0.0778 - val_loss: -420678172672.0000
Epoch 19/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1045 - loss: -416582696960.0000 - val_accuracy: 0.0778 - val_loss: -429500497920.0000
Epoch 20/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1058 - loss: -405992964096.0000 - val_accuracy: 0.0778 - val_loss: -438327967744.0000
Epoch 21/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1129 - loss: -418862268416.0000 - val_accuracy: 0.0778 - val_loss: -447366529024.0000
Epoch 22/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0885 - loss: -420143824896.0000 - val_accuracy: 0.0778 - val_loss: -456419180544.0000
Epoch 23/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1109 - loss: -440002871296.0000 - val_accuracy: 0.0778 - val_loss: -465638948864.0000
Epoch 24/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.1006 - loss: -449854668800.0000 - val_accuracy: 0.0778 - val_loss: -474957348864.0000
Epoch 25/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1115 - loss: -440899436544.0000 - val_accuracy: 0.0778 - val_loss: -484278992896.0000
Epoch 26/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.1032 - loss: -477937434624.0000 - val_accuracy: 0.0778 - val_loss: -493832044544.0000
Epoch 27/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1262 - loss: -468814987264.0000 - val_accuracy: 0.0778 - val_loss: -503495524352.0000
Epoch 28/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1120 - loss: -498233540608.0000 - val_accuracy: 0.0778 - val_loss: -513271365632.0000
Epoch 29/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1055 - loss: -498534121472.0000 - val_accuracy: 0.0778 - val_loss: -523098783744.0000
Epoch 30/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1165 - loss: -498408521728.0000 - val_accuracy: 0.0778 - val_loss: -533021851648.0000
Epoch 31/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1064 - loss: -517916524544.0000 - val_accuracy: 0.0778 - val_loss: -543158304768.0000
Epoch 32/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0989 - loss: -524815302656.0000 - val_accuracy: 0.0778 - val_loss: -553237020672.0000
Epoch 33/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1080 - loss: -541785915392.0000 - val_accuracy: 0.0778 - val_loss: -563595247616.0000
Epoch 34/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1189 - loss: -539054505984.0000 - val_accuracy: 0.0778 - val_loss: -573900783616.0000
Epoch 35/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1105 - loss: -548222500864.0000 - val_accuracy: 0.0778 - val_loss: -584466366464.0000
Epoch 36/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1107 - loss: -565137113088.0000 - val_accuracy: 0.0778 - val_loss: -595020152832.0000
Epoch 37/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1176 - loss: -563462733824.0000 - val_accuracy: 0.0778 - val_loss: -605736861696.0000
Epoch 38/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0970 - loss: -583308279808.0000 - val_accuracy: 0.0778 - val_loss: -616707129344.0000
Epoch 39/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1000 - loss: -585500917760.0000 - val_accuracy: 0.0778 - val_loss: -627536691200.0000
Epoch 40/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1247 - loss: -581423857664.0000 - val_accuracy: 0.0778 - val_loss: -638593859584.0000
Epoch 41/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1068 - loss: -596351909888.0000 - val_accuracy: 0.0778 - val_loss: -649758965760.0000
Epoch 42/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1063 - loss: -620323405824.0000 - val_accuracy: 0.0778 - val_loss: -661058093056.0000
Epoch 43/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0948 - loss: -648192786432.0000 - val_accuracy: 0.0778 - val_loss: -672597934080.0000
Epoch 44/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0968 - loss: -667151433728.0000 - val_accuracy: 0.0778 - val_loss: -684070666240.0000
Epoch 45/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0950 - loss: -667017609216.0000 - val_accuracy: 0.0778 - val_loss: -695789486080.0000
Epoch 46/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1090 - loss: -675757096960.0000 - val_accuracy: 0.0778 - val_loss: -707454304256.0000
Epoch 47/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1104 - loss: -658118410240.0000 - val_accuracy: 0.0778 - val_loss: -719294955520.0000
Epoch 48/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1013 - loss: -719089369088.0000 - val_accuracy: 0.0778 - val_loss: -731387985920.0000
Epoch 49/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1105 - loss: -690564759552.0000 - val_accuracy: 0.0778 - val_loss: -743360954368.0000
Epoch 50/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1238 - loss: -690338725888.0000 - val_accuracy: 0.0778 - val_loss: -755495993344.0000
Epoch 51/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1112 - loss: -727596662784.0000 - val_accuracy: 0.0778 - val_loss: -768021168128.0000
Epoch 52/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0980 - loss: -766286888960.0000 - val_accuracy: 0.0778 - val_loss: -780592742400.0000
Epoch 53/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1064 - loss: -765175595008.0000 - val_accuracy: 0.0778 - val_loss: -793123422208.0000
Epoch 54/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1019 - loss: -756075790336.0000 - val_accuracy: 0.0778 - val_loss: -805654429696.0000
Epoch 55/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1044 - loss: -728898928640.0000 - val_accuracy: 0.0778 - val_loss: -818504728576.0000
Epoch 56/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1074 - loss: -783981477888.0000 - val_accuracy: 0.0778 - val_loss: -831578570752.0000
Epoch 57/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0999 - loss: -802621816832.0000 - val_accuracy: 0.0778 - val_loss: -844527239168.0000
Epoch 58/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.1070 - loss: -820124450816.0000 - val_accuracy: 0.0778 - val_loss: -857744867328.0000
Epoch 59/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1152 - loss: -802140717056.0000 - val_accuracy: 0.0778 - val_loss: -870948077568.0000
Epoch 60/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1040 - loss: -842280337408.0000 - val_accuracy: 0.0778 - val_loss: -884391084032.0000
Epoch 61/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0950 - loss: -887958667264.0000 - val_accuracy: 0.0778 - val_loss: -898154496000.0000
Epoch 62/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1119 - loss: -876113297408.0000 - val_accuracy: 0.0778 - val_loss: -911603728384.0000
Epoch 63/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.1047 - loss: -893382426624.0000 - val_accuracy: 0.0778 - val_loss: -925521543168.0000
Epoch 64/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0990 - loss: -893864443904.0000 - val_accuracy: 0.0778 - val_loss: -939351080960.0000
Epoch 65/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1035 - loss: -934437519360.0000 - val_accuracy: 0.0778 - val_loss: -953556402176.0000
Epoch 66/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0950 - loss: -944162340864.0000 - val_accuracy: 0.0778 - val_loss: -967624163328.0000
Epoch 67/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1080 - loss: -967319814144.0000 - val_accuracy: 0.0778 - val_loss: -981852291072.0000
Epoch 68/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1073 - loss: -972404293632.0000 - val_accuracy: 0.0778 - val_loss: -996213391360.0000
Epoch 69/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1209 - loss: -917175730176.0000 - val_accuracy: 0.0778 - val_loss: -1010625478656.0000
Epoch 70/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1034 - loss: -978659508224.0000 - val_accuracy: 0.0778 - val_loss: -1025340407808.0000
Epoch 71/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1156 - loss: -947807977472.0000 - val_accuracy: 0.0778 - val_loss: -1040050552832.0000
Epoch 72/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1139 - loss: -1013079867392.0000 - val_accuracy: 0.0778 - val_loss: -1055247958016.0000
Epoch 73/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1049 - loss: -1019772207104.0000 - val_accuracy: 0.0778 - val_loss: -1070076854272.0000
Epoch 74/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1068 - loss: -1022729912320.0000 - val_accuracy: 0.0778 - val_loss: -1085274587136.0000
Epoch 75/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0936 - loss: -1055522947072.0000 - val_accuracy: 0.0778 - val_loss: -1100601753600.0000
Epoch 76/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1125 - loss: -1023888261120.0000 - val_accuracy: 0.0778 - val_loss: -1116006514688.0000
Epoch 77/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1029 - loss: -1093128093696.0000 - val_accuracy: 0.0778 - val_loss: -1131583504384.0000
Epoch 78/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1007 - loss: -1063833632768.0000 - val_accuracy: 0.0778 - val_loss: -1147207417856.0000
Epoch 79/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1042 - loss: -1097796419584.0000 - val_accuracy: 0.0778 - val_loss: -1163074469888.0000
Epoch 80/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1081 - loss: -1099989778432.0000 - val_accuracy: 0.0778 - val_loss: -1179057389568.0000
Epoch 81/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0983 - loss: -1129685450752.0000 - val_accuracy: 0.0778 - val_loss: -1195162599424.0000
Epoch 82/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1100 - loss: -1149663051776.0000 - val_accuracy: 0.0778 - val_loss: -1211297955840.0000
Epoch 83/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.1027 - loss: -1175283957760.0000 - val_accuracy: 0.0778 - val_loss: -1227613929472.0000
Epoch 84/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.1154 - loss: -1164462129152.0000 - val_accuracy: 0.0778 - val_loss: -1244057698304.0000
Epoch 85/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1113 - loss: -1168392585216.0000 - val_accuracy: 0.0778 - val_loss: -1260685361152.0000
Epoch 86/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1093 - loss: -1187116482560.0000 - val_accuracy: 0.0778 - val_loss: -1277434265600.0000
Epoch 87/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1030 - loss: -1182951276544.0000 - val_accuracy: 0.0778 - val_loss: -1294285406208.0000
Epoch 88/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0882 - loss: -1269649768448.0000 - val_accuracy: 0.0778 - val_loss: -1311305236480.0000
Epoch 89/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1161 - loss: -1256132706304.0000 - val_accuracy: 0.0778 - val_loss: -1328319823872.0000
Epoch 90/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1127 - loss: -1251408347136.0000 - val_accuracy: 0.0778 - val_loss: -1345671921664.0000
Epoch 91/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1134 - loss: -1286005719040.0000 - val_accuracy: 0.0778 - val_loss: -1362998722560.0000
Epoch 92/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1002 - loss: -1315944267776.0000 - val_accuracy: 0.0778 - val_loss: -1380655824896.0000
Epoch 93/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1048 - loss: -1338542784512.0000 - val_accuracy: 0.0778 - val_loss: -1398236250112.0000
Epoch 94/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1155 - loss: -1329817452544.0000 - val_accuracy: 0.0778 - val_loss: -1416200978432.0000
Epoch 95/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.1040 - loss: -1407253217280.0000 - val_accuracy: 0.0778 - val_loss: -1434118127616.0000
Epoch 96/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1024 - loss: -1424789078016.0000 - val_accuracy: 0.0778 - val_loss: -1452198854656.0000
Epoch 97/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0958 - loss: -1368180916224.0000 - val_accuracy: 0.0778 - val_loss: -1470252711936.0000
Epoch 98/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0981 - loss: -1454648459264.0000 - val_accuracy: 0.0778 - val_loss: -1488836493312.0000
Epoch 99/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1117 - loss: -1424059531264.0000 - val_accuracy: 0.0778 - val_loss: -1507257745408.0000
Epoch 100/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1106 - loss: -1471441403904.0000 - val_accuracy: 0.0778 - val_loss: -1526077456384.0000

In [36]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [37]:
##Load Tensorboard Extension 

%load_ext tensorboard

In [43]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 2684), started 0:14:12 ago. (Use '!kill 2684' to kill it.)

In [44]:
###Load the pickle file